# Generated by Django 4.0.3 on 2022-10-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0003_registerstudents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_no', models.IntegerField(unique=True)),
                ('subject_name', models.CharField(max_length=200)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='SubjectsImages/')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
    ]
