# Generated by Django 4.0.3 on 2022-10-10 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0005_subjects_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test1', models.IntegerField(blank=True, null=True)),
                ('Test2', models.IntegerField(blank=True, null=True)),
                ('Test3', models.IntegerField(blank=True, null=True)),
                ('Test4', models.IntegerField(blank=True, null=True)),
                ('Test5', models.IntegerField(blank=True, null=True)),
                ('MidTerm', models.IntegerField(blank=True, null=True)),
                ('Term', models.IntegerField(blank=True, null=True)),
                ('Average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('registerstudents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimosoApp.registerstudents')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimosoApp.subjects')),
            ],
            options={
                'verbose_name_plural': 'Marks',
            },
        ),
    ]
