# Generated by Django 4.0.3 on 2022-10-11 17:11

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0006_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='marks',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
