# Generated by Django 4.0.3 on 2022-10-13 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0007_marks_marks_marks_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='Average',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='MidTerm',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Term',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Test1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Test2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Test3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Test4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='Test5',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='total_marks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='GeneralResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('physics', models.IntegerField(blank=True, default=0, null=True)),
                ('physics_total_marks', models.IntegerField(blank=True, default=0, null=True)),
                ('physics_average', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('chemistry', models.IntegerField(blank=True, default=0, null=True)),
                ('chemistry_total_marks', models.IntegerField(blank=True, default=0, null=True)),
                ('chemistry_average', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('biology', models.IntegerField(blank=True, default=0, null=True)),
                ('biology_total_marks', models.IntegerField(blank=True, default=0, null=True)),
                ('biology_average', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('civics', models.IntegerField(blank=True, default=0, null=True)),
                ('civics_total_marks', models.IntegerField(blank=True, default=0, null=True)),
                ('civics_average', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('history', models.IntegerField(blank=True, default=0, null=True)),
                ('history_total_marks', models.IntegerField(blank=True, default=0, null=True)),
                ('history_average', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('english', models.IntegerField(blank=True, default=0, null=True)),
                ('english_total_marks', models.IntegerField(blank=True, default=0, null=True)),
                ('english_average', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('kiswahili', models.IntegerField(blank=True, default=0, null=True)),
                ('kiswahili_total_marks', models.IntegerField(blank=True, default=0, null=True)),
                ('kiswahili_average', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('mathematics', models.IntegerField(blank=True, default=0, null=True)),
                ('mathematics_total_marks', models.IntegerField(blank=True, default=0, null=True)),
                ('mathematics_average', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('geography', models.IntegerField(blank=True, default=0, null=True)),
                ('geography_total_marks', models.IntegerField(blank=True, default=0, null=True)),
                ('geography_average', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('student_total', models.IntegerField(blank=True, null=True)),
                ('student_average', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('student_point', models.CharField(blank=True, max_length=200, null=True)),
                ('student_grade', models.CharField(blank=True, max_length=200, null=True)),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimosoApp.registerstudents')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimosoApp.subjects')),
            ],
            options={
                'verbose_name_plural': 'GeneralResults',
            },
        ),
    ]
