# Generated by Django 4.0.3 on 2022-10-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0008_alter_marks_average_alter_marks_midterm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalresults',
            name='subjects',
        ),
    ]
