# Generated by Django 4.0.3 on 2022-10-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0009_remove_generalresults_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalresults',
            name='history_average',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='generalresults',
            name='student_average',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='generalresults',
            name='student_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
