# Generated by Django 4.0.3 on 2022-10-13 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0010_alter_generalresults_history_average_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalresults',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimosoApp.registerstudents', unique=True),
        ),
    ]
