# Generated by Django 4.0.3 on 2022-10-13 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0011_alter_generalresults_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalresults',
            name='students',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DimosoApp.registerstudents'),
        ),
    ]
