# Generated by Django 4.0.3 on 2022-10-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0013_importantinformations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantinformations',
            name='debt',
            field=models.CharField(blank=True, choices=[(' ', 'Fill Here-------'), ('NO', 'NO'), ('Yes', 'Yes')], max_length=30, null=True),
        ),
    ]
