# Generated by Django 4.0.3 on 2022-10-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0014_alter_importantinformations_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantinformations',
            name='debt',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('Yes', 'Yes')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='importantinformations',
            name='habit',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=200, null=True),
        ),
    ]
