# Generated by Django 4.0.3 on 2022-10-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0015_alter_importantinformations_debt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantinformations',
            name='debt',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=30, null=True),
        ),
    ]
