# Generated by Django 4.0.3 on 2022-10-14 09:21

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0016_alter_importantinformations_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendSmsEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='@gmail.com', max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, default='+255', max_length=13, null=True, unique=True)),
                ('send_through_email', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('send_through_text', models.TextField(blank=True, null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('students', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DimosoApp.registerstudents')),
            ],
            options={
                'verbose_name_plural': 'SendSmsEmail',
            },
        ),
    ]
