# Generated by Django 4.0.3 on 2022-10-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0017_sendsmsemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PangiliaAlama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_start', models.CharField(blank=True, max_length=3, null=True)),
                ('B_start', models.CharField(blank=True, max_length=3, null=True)),
                ('C_start', models.CharField(blank=True, max_length=3, null=True)),
                ('D_start', models.CharField(blank=True, max_length=3, null=True)),
                ('E_start', models.CharField(blank=True, max_length=3, null=True)),
                ('F_start', models.CharField(blank=True, max_length=3, null=True)),
                ('A_end', models.CharField(blank=True, max_length=3, null=True)),
                ('B_end', models.CharField(blank=True, max_length=3, null=True)),
                ('C_end', models.CharField(blank=True, max_length=3, null=True)),
                ('D_end', models.CharField(blank=True, max_length=3, null=True)),
                ('E_end', models.CharField(blank=True, max_length=3, null=True)),
                ('F_end', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'verbose_name_plural': 'PangiliaAlama',
            },
        ),
    ]
