# Generated by Django 4.0.3 on 2022-10-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0021_alter_generalresults_student_average_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='Average',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='marks',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
