# Generated by Django 4.0.3 on 2022-10-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0022_alter_marks_average_alter_marks_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='Average',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
        migrations.AlterField(
            model_name='marks',
            name='total_marks',
            field=models.IntegerField(),
        ),
    ]
