# Generated by Django 4.0.3 on 2022-10-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimosoApp', '0026_individualresults_tabia_marks_subject_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('MULTI TEACHER', 'MULTI TEACHER'), ('PHYSICS TEACHER', 'PHYSICS TEACHER'), ('CHEMISTRY TEACHER', 'CHEMISTRY TEACHER'), ('BIOLOGY TEACHER', 'BIOLOGY TEACHER'), ('ENGLISH TEACHER', 'ENGLISH TEACHER'), ('CIVICS TEACHER', 'CIVICS TEACHER'), ('MATHEMATICS TEACHER', 'MATHEMATICS TEACHER'), ('HISTORY TEACHER', 'HISTORY TEACHER'), ('GEOGRAPHY TEACHER', 'GEOGRAPHY TEACHER'), ('KISWAHILI TEACHER', 'KISWAHILI TEACHER')], max_length=50, verbose_name='role'),
        ),
    ]
